### ISSUE TITLE
Getting this error 

### ISSUE THREAD

**Issue by atuljha23** [Acidham/uebersicht-airpod-status#5]
Traceback (most recent call last): File "AirPods.widget/bt.py", line 96, in main() File "AirPods.widget/bt.py", line 88, in main connected_list = get_device_html() File "AirPods.widget/bt.py", line 69, in get_device_html airpods: list = paired_airpods() File "AirPods.widget/bt.py", line 39, in paired_airpods devices: dict = jsn['SPBluetoothDataType'][0]['devices_list'] KeyError: 'devices_list'

**Comment by Acidham** [comment]
- Which macOS version are you on?
- What AirPods models are you using?
